# Generated by Django 4.1.1 on 2022-12-17 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
