# Generated by Django 4.1.1 on 2023-05-11 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
