version: '3.8'

services:

  django:
    build:
      context: ./
      dockerfile: ./dockerfiles/django/Dockerfile
    entrypoint: bash ./django-launcher.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      DOMAIN: ${DOMAIN}
      DOMAIN_URL: ${DOMAIN_URL}
      REDIS_URI: ${REDIS_URI}
      REDIS_PORT: ${REDIS_PORT}
    expose:
      - 8000
      - 6831
    depends_on:
      - redis

  redis:
    image: redis:alpine
    expose:
      - ${REDIS_PORT}

  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/usr/src/app/
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    depends_on:
      - django
      - gulp

  gulp:
    build:
      context: ./
      dockerfile: ./dockerfiles/gulp/Dockerfile
    command: bash gulp-launcher.sh
    volumes:
      - .:/usr/src/app/
    ports:
      - 3000:3000
