"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = (
    os.environ.get("ALLOWED_HOSTS", ".localhost,127.0.0.1,[::1]").split(",")
    + [os.environ.get("HOST_IP")]
    + [os.environ.get("POD_IP")]
    + [os.environ.get("WEB_SERVICE_HOST")]
    + ["django"]
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "channels",
    "django_prometheus",
    "app.website",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "app.website.context_processors.customs",
            ]
        },
    }
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "es"

LANGUAGES = [("es", _("Español")), ("en", _("Inglés"))]

LOCALE_PATHS = (BASE_DIR / "locale/",)

TIME_ZONE = "CET"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = os.environ.get("STATIC_ROOT")
STATIC_URL = os.environ.get("STATIC_URL")
THUMBOR_URL = os.environ.get("THUMBOR_URL")
THUMBOR_ENABLED = os.environ.get("THUMBOR_ENABLED", "False") == "True"


DOMAIN = os.environ.get("DOMAIN")
DOMAIN_URL = (
    os.environ.get("DOMAIN_URL")[:-1]
    if os.environ.get("DOMAIN_URL")[-1:] == "/"
    else os.environ.get("DOMAIN_URL")
)

# Metrics and observability
JAEGER_AGENT_HOST = os.environ.get("JAEGER_AGENT_HOST")
JAEGER_AGENT_PORT = os.environ.get("JAEGER_AGENT_PORT")
JAEGER_SERVICE_NAME = os.environ.get("JAEGER_SERVICE_NAME")

# Fix nginx proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = [DOMAIN_URL]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [os.environ.get("REDIS_URI")]},
    }
}

ASGI_APPLICATION = "core.asgi.application"
STATIC_URL = "/static/"
